name = "DS19Presentation"
uuid = "c52eaf16-6d25-11e9-34da-d5c7cd6dfd33"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataDepsGenerators = "a14fa8ac-7845-53f2-854f-e9bba4c623ff"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NuclearSurfaceVibrations = "61377714-a6e6-11e8-0d55-23ea14e6950b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StorageGraphs = "fa9e2bbc-20aa-512b-a47b-5a4d8687aaeb"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TaylorIntegration = "92b13dbe-c966-51a2-8445-caca9f8a7d42"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
