name = "DS19Presentation"
uuid = "c52eaf16-6d25-11e9-34da-d5c7cd6dfd33"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataDepsGenerators = "a14fa8ac-7845-53f2-854f-e9bba4c623ff"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NuclearSurfaceVibrations = "61377714-a6e6-11e8-0d55-23ea14e6950b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StorageGraphs = "fa9e2bbc-20aa-512b-a47b-5a4d8687aaeb"
